services:

    #
    # Services
    #
    elcodi.provider.category_tree:
        class: Elcodi\Component\Product\Services\CategoryTree
        arguments:
            - @elcodi.repository.category

    elcodi.provider.product_collection:
        class: Elcodi\Component\Product\Services\ProductCollectionProvider
        arguments:
            - @elcodi.repository.product
            - ?@elcodi.store_uses_stock
