Elcodi\Component\Store\Entity\Store:
    type: entity
    repositoryClass: Elcodi\Component\Store\Repository\StoreRepository
    table: store

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        leitmotiv:
            column: leitmotiv
            type: string
            length: 255
            nullable: true
        phone:
            column: phone
            type: string
            length: 255
            nullable: true
        email:
            column: email
            type: string
            length: 255
            nullable: true
        tracker:
            column: tracker
            type: string
            length: 255
            nullable: true
        template:
            column: template
            type: string
            length: 255
            nullable: true
        underConstruction:
            column: under_construction
            type: boolean
        useStock:
            column: use_stock
            type: boolean
        color:
            column: color
            type: string
            length: 255
            nullable: true

        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean
            nullable: false

    manyToOne:
        taxAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: tax_address_id
                referencedColumnName: id
        physicalAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: physical_address_id
                referencedColumnName: id
        defaultLanguage:
            targetEntity: Elcodi\Component\Language\Entity\Interfaces\LanguageInterface
            joinColumn:
                name: default_language_iso
                referencedColumnName: iso
        defaultCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                name: default_currency_iso
                referencedColumnName: iso

    oneToOne:
        identityImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: identity_image_id
                referencedColumnName: id
                nullable: true
        identityLogo:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: identity_logo_id
                referencedColumnName: id
                nullable: true
        identitySecondaryLogo:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: identity_secondary_logo_id
                referencedColumnName: id
                nullable: true
        identityMobileLogo:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: identity_mobile_logo_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
